// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCICSnZ9csNpCreV9T1TGazOhgdmgCvvMQ',
    appId: '1:1085906236897:web:bb07467a72e2e8e324cea0',
    messagingSenderId: '1085906236897',
    projectId: 'ortiqjan-12345',
    authDomain: 'ortiqjan-12345.firebaseapp.com',
    storageBucket: 'ortiqjan-12345.firebasestorage.app',
    measurementId: 'G-W5R6J8V7ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACeRKfd8kWXJ4iF1wXGc2d1HZtUs4I8_M',
    appId: '1:1085906236897:android:960a09742499e61224cea0',
    messagingSenderId: '1085906236897',
    projectId: 'ortiqjan-12345',
    storageBucket: 'ortiqjan-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD0v2bunntc05qU-JwNkbX9CH51AmCSY8',
    appId: '1:1085906236897:ios:02214a0cc97a04ba24cea0',
    messagingSenderId: '1085906236897',
    projectId: 'ortiqjan-12345',
    storageBucket: 'ortiqjan-12345.firebasestorage.app',
    iosBundleId: 'uz.ortiqjan.ortiqjan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD0v2bunntc05qU-JwNkbX9CH51AmCSY8',
    appId: '1:1085906236897:ios:02214a0cc97a04ba24cea0',
    messagingSenderId: '1085906236897',
    projectId: 'ortiqjan-12345',
    storageBucket: 'ortiqjan-12345.firebasestorage.app',
    iosBundleId: 'uz.ortiqjan.ortiqjan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCICSnZ9csNpCreV9T1TGazOhgdmgCvvMQ',
    appId: '1:1085906236897:web:795c1730e30e1dba24cea0',
    messagingSenderId: '1085906236897',
    projectId: 'ortiqjan-12345',
    authDomain: 'ortiqjan-12345.firebaseapp.com',
    storageBucket: 'ortiqjan-12345.firebasestorage.app',
    measurementId: 'G-7PMBY84Z74',
  );
}
